In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('NewYearEvents.csv')

In [3]:
df

,Name_of_event,Time and Date,Location,Cost_of_Ticket
0,The Lalit Mumbai - Grand New Year Festival 202...,December 31 | 9PM - January 1 | 3AM,"The Lalit Mumbai, Mumbai",2000 onwards
1,BIGGEST NEW YEAR BASH 2023 @ CIDCO Exhibition ...,December 31 | 8PM - January 1 | 1AM,"CIDCO Exhibition & Convention Centre, Navi Mumbai",2000 onwards
2,Novotel Juhu - New Year's Eve Bollywood Bash |...,December 31 | 9PM - January 1 | 3AM,"Novotel Mumbai Juhu Beach, Mumbai",3500 onwards
3,#High2Happiness: New Year Brunch Blast @ Gloca...,December 31 | 11:30AM - January 1 | 3:30PM,"Glocal Junction, Mumbai",Free
4,New Year Bash at Imagicaa | NYE 2023,December 31 | 10AM - January 1 | 12AM,"Imagica Theme Park, Khopoli, Lonavala",1179 onwards
...,...,...,...,...
72,NEW YEAR EVE @ SOHO-DELHI,December 31 | 10PM - January 1 | 3AM,Soho Club Delhi,₹3000 onwards
73,New Year's Eve - Ministry Of Sound,December 31 | 8PM,"Ministry of Sound Brewery, Noida",₹5000 onwards
74,SOLACITY : LET THE NEW YOU OUT : 31st Dec' 2022,December 31 | 8PM - January 1 | 2AM,"Mariegold Retreats, Delhi",₹4999 onwards
75,Disco'22 - New Year's Eve @ Imperfecto Hauz Kh...,December 31 | 8PM - January 1 | 12AM,"Imperfecto Hauz Khas, Delhi",₹5000
76,NEW YEAR CELEBRATION AT REGENTA SUITES GURUGRAM,December 31 | 7PM - January 1 | 12AM,"Regenta Suites Gurugram, Gurugram",₹5900 onwards

In [4]:
df['Name_of_event']

0     The Lalit Mumbai - Grand New Year Festival 202...
1     BIGGEST NEW YEAR BASH 2023 @ CIDCO Exhibition ...
2     Novotel Juhu - New Year's Eve Bollywood Bash |...
3     #High2Happiness: New Year Brunch Blast @ Gloca...
4                  New Year Bash at Imagicaa | NYE 2023
                            ...
72                           NEW YEAR EVE @ SOHO-DELHI
73                  New Year's Eve - Ministry Of Sound
74    SOLACITY : LET THE NEW YOU OUT :  31st Dec' 2022
75    Disco'22 - New Year's Eve @ Imperfecto Hauz Kh...
76     NEW YEAR CELEBRATION AT REGENTA SUITES GURUGRAM
Name: Name_of_event, Length: 77, dtype: object

In [5]:
df['Name_of_event']

0     The Lalit Mumbai - Grand New Year Festival 202...
1     BIGGEST NEW YEAR BASH 2023 @ CIDCO Exhibition ...
2     Novotel Juhu - New Year's Eve Bollywood Bash |...
3     #High2Happiness: New Year Brunch Blast @ Gloca...
4                  New Year Bash at Imagicaa | NYE 2023
                            ...
72                           NEW YEAR EVE @ SOHO-DELHI
73                  New Year's Eve - Ministry Of Sound
74    SOLACITY : LET THE NEW YOU OUT :  31st Dec' 2022
75    Disco'22 - New Year's Eve @ Imperfecto Hauz Kh...
76     NEW YEAR CELEBRATION AT REGENTA SUITES GURUGRAM
Name: Name_of_event, Length: 77, dtype: object

In [6]:
def namefunc(x):
    for i in x:
        j=i.split('|')
        k=j[0]
        return k

In [7]:
#df['Name_of_event']=df['Name_of_event'].apply(namefunc)

In [8]:
df

,Name_of_event,Time and Date,Location,Cost_of_Ticket
0,The Lalit Mumbai - Grand New Year Festival 202...,December 31 | 9PM - January 1 | 3AM,"The Lalit Mumbai, Mumbai",2000 onwards
1,BIGGEST NEW YEAR BASH 2023 @ CIDCO Exhibition ...,December 31 | 8PM - January 1 | 1AM,"CIDCO Exhibition & Convention Centre, Navi Mumbai",2000 onwards
2,Novotel Juhu - New Year's Eve Bollywood Bash |...,December 31 | 9PM - January 1 | 3AM,"Novotel Mumbai Juhu Beach, Mumbai",3500 onwards
3,#High2Happiness: New Year Brunch Blast @ Gloca...,December 31 | 11:30AM - January 1 | 3:30PM,"Glocal Junction, Mumbai",Free
4,New Year Bash at Imagicaa | NYE 2023,December 31 | 10AM - January 1 | 12AM,"Imagica Theme Park, Khopoli, Lonavala",1179 onwards
...,...,...,...,...
72,NEW YEAR EVE @ SOHO-DELHI,December 31 | 10PM - January 1 | 3AM,Soho Club Delhi,₹3000 onwards
73,New Year's Eve - Ministry Of Sound,December 31 | 8PM,"Ministry of Sound Brewery, Noida",₹5000 onwards
74,SOLACITY : LET THE NEW YOU OUT : 31st Dec' 2022,December 31 | 8PM - January 1 | 2AM,"Mariegold Retreats, Delhi",₹4999 onwards
75,Disco'22 - New Year's Eve @ Imperfecto Hauz Kh...,December 31 | 8PM - January 1 | 12AM,"Imperfecto Hauz Khas, Delhi",₹5000
76,NEW YEAR CELEBRATION AT REGENTA SUITES GURUGRAM,December 31 | 7PM - January 1 | 12AM,"Regenta Suites Gurugram, Gurugram",₹5900 onwards

In [25]:
for i in df['Time and Date']:
    i=i.replace('-','to')
    i=i.replace('|','')
    print(i)

December 31  9PM to January 1  3AM
December 31  8PM to January 1  1AM
December 31  9PM to January 1  3AM
December 31  11:30AM to January 1  3:30PM
December 31  10AM to January 1  12AM
December 31  8PM to January 1  3AM
December 31  9PM to January 1  3AM
December 31  9PM to January 1  3AM
December 31  8:30PM to January 1  2:00AM
December 31  3PM to January 1  11AM
December 31  3PM to January 1  11AM
December 31  6:05PM to January 1  12:00AM
December 31  6PM to January 1  2AM
December 31  7PM to January 1  5AM
December 31  8PM to January 1  1AM
December 31  7PM
December 31  8PM Onwards
December 31  7PM to January 1  1AM
December 31  8PM to January 1  1AM
December 31  7PM to January 1  12AM
December 31  7PM to January 1  12AM
December 31  7PM to January 1  1AM
December 31  8PM to January 1  1AM
December 31  8PM to January 1  12AM
December 31  8PM to January 1  12AM
December 31  6PM to January 1  1AM
December 31  8PM to January 1  1AM
December 31  8PM to January 1  1AM
December 31  7:30PM to January 1  1:00AM
December 31  7PM to January 1  12AM
December 31  7PM to January 1  1AM
December 31  8PM to January 1  1AM
December 31  8PM
December 31  7PM to January 1  12AM
December 31  9PM to January 1  4AM
December 31  8PM to January 1  4AM
December 31  8PM
December 31  9PM to January 1  4AM
December 31  7PM to January 1  12AM
December 31  7PM to January 1  12AM
December 31  8PM to January 1  1AM
December 31  8PM to January 1  12AM
December 31  3PM to January 1  12AM
December 31  6PM to January 1  12:30AM
December 31  8PM to January 1  2AM
December 31  8PM to January 1  2AM
December 30  5PM to December 31  4AM
December 31  6PM to January 1  3AM
December 31  8PM to January 1  2AM
December 31  8PM to January 1  2AM
December 31  5PM
December 31  8PM to January 1  1AM
January 7  6PM to January 8  10PM
December 31
December 31  8PM to January 1  3AM
December 31  9PM to January 1  3AM
December 31  6PM to January 1  2AM
December 31  7PM to January 1  2AM
December 31  8PM to January 1  1AM
December 31  5PM to January 1  1AM
December 31  7:30PM to January 1  2:00AM
December 31  8PM to January 1  12AM
December 31  8:30PM
December 31  7PM to January 1  2AM
December 31  7PM
December 31  8:30PM to January 1  1:00AM
December 31  6PM to January 1  12AM
December 31  5PM
December 31  6PM to January 1  1AM
December 31  6PM
December 31  6PM to January 1  6AM
December 31  6:30PM
December 31  10PM to January 1  3AM
December 31  8PM
December 31  8PM to January 1  2AM
December 31  8PM to January 1  12AM
December 31  7PM to January 1  12AM

In [44]:
for i in df['Location']:
    i=i.split(' ',1)
    print(i)

['The', 'Lalit Mumbai, Mumbai']
['CIDCO', 'Exhibition & Convention Centre, Navi Mumbai']
['Novotel', 'Mumbai Juhu Beach, Mumbai']
['Glocal', 'Junction, Mumbai']
['Imagica', 'Theme Park, Khopoli, Lonavala']
['Kitty', 'Su Mumbai, Mumbai']
['Tap', 'Resto Bar New Link Road Andheri West']
['The', 'Forest Club Resort, Karjat']
['Mahalakshmi', 'Race Course, Mumbai']
['Pawna', 'Lake Camping Pawnacamp, Lonavala']
['Revdanda', 'Fort, Alibaug']
['Karnala', 'Bird Sanctuary, Navi Mumbai']
['Sea', 'Lounge The Beach Cafe, Thane']
['Kalyan-Murbad', 'Road, Thane']
['Mayfield', 'Estate, Pune']
['Penthouze', 'Nightlife, Pune']
['The', 'Cult - Terra | House, Pune']
['Yolo', 'Gastro Lounge, Pune']
['The', 'Forest Club Resort, Karjat']
['Drama', '9, Pune']
['Prism', 'Club & Kitchen, Hyderabad']
['Rancho', 'De Caballos, Hyderabad']
['Meridian', 'Cricket Ground, Hyderabad']
['Taj', 'Deccan, Hyderabad']
['Novotel', 'Hyderabad Airport, Hyderabad']
['HITEX', 'Exhibition Center, Hyderabad']
['Taj', 'West End, Bengaluru']
['JW', 'Marriott Hotel Bengaluru, Bengaluru']
['Taj', 'Yeshwantpur, Bengaluru, Bengaluru']
['The', 'Lalit Ashok, Bengaluru']
['XU,', 'Bengaluru']
['Taj', 'MG Road, Bengaluru']
['Marbela', 'Beach Resort, Goa']
['Las', 'Olas, Baga Beach, Goa']
['The', 'Secret Room Goa, Goa']
['LPK', 'Waterfront Club, Goa']
['GLORY,', 'Goa, Goa']
['The', 'White Goa, Goa']
['Phoenix', 'Marketcity, Chennai']
['Le', 'Royal Méridien Chennai, Chennai']
["Watson's", 'Chennai, Chennai']
['Lower', 'Deck Club, Chennai']
['Tamilnadu', 'Tourism Beach Resort Private Beach, Mahabalipuram']
['Hotel', 'Chennai Le Palace, Chennai']
['JW', 'Marriott Hotel, Kolkata']
['Vivada', 'Cruise, Kolkata']
['JW', 'Marriott Hotel, Kolkata']
['Malt,', 'Kolkata']
['Capella', '(Altair Boutique Hotel), Kolkata']
['The', 'Stadel, Kolkata']
['Dr.', 'Ram Manohar Lohia Park Gomtinagar, Lucknow']
['The', 'Grand Casa, Lucknow']
['U', 'P SANGEET NATAK AKADEMI, Lucknow']
['JECC,', 'Jaipur']
['Club', 'Naila, Jaipur']
['Disco', 'Valley, Jaipur']
['Hotel', 'Rockwell, Jaipur']
['Once', 'Upon A Terrace - OUT, Jaipur']
['Nirwana', 'Hometel Jaipur, Jaipur']
['Sankosh', 'Music Fest, Guwahati']
['Forest', 'Hill Golf & Country Club Resort, Mohali']
['The', 'Mohali Club || Wyndham Chandigarh Mohali, Chandigarh']
['The', 'Finch Chandigarh, Chandigarh']
['Baithak', 'The Craft Kitchen, Best Family Restaurant in Chandigarh, Chandigarh']
['Sky', 'Grill Restaurant Mohali, Mohali']
['Aurum', 'Cafe Bar and Sky Lounge, Mohali']
['Krishna', 'Farm, Ahmedabad']
['Green', 'Palace, Ahmedabad']
['Dandi', 'Bridge, Ahmedabad']
['Vrundavan', 'Premium Lawn, Ahmedabad']
['MAAHOL,', 'Ahmedabad']
['Bodakdev', 'Party Plot, Ahmedabad']
['Soho', 'Club Delhi']
['Ministry', 'of Sound Brewery, Noida']
['Mariegold', 'Retreats, Delhi']
['Imperfecto', 'Hauz Khas, Delhi']
['Regenta', 'Suites Gurugram, Gurugram']